### ISSUE TITLE
[Suggestion] provide an object-oriented API

### ISSUE THREAD

**Issue by stof** [beberlei/hdrhistogram-php#1]
Currently, the API provides a way to create a resource, and then a bunch of functions manipulating this resource. It even provides a custom iteration API.

IMO, an object-oriented API might be better (this is the example of the readme rewritten in this way):

```php
$hdr = new HdrHistogram(1, 3600000, 3);
$hdr->recordValue(1337);
$hdr->recordValues(array(42, 100)); // Or through a variadic way, but then having 2 methods is weird

printf(
    'Mean: %d Min: %d Max: %d Count(42): %d Perc(95): %d',
    $hdr->mean(),
    $hdr->min(),
    $hdr->max(),
    $hdr->countAtValue(42),
    $hdr->valueAtPercentile(95)
);

// HdrHistogram implements Traversable to native iteration
foreach ($hdr as $data) {
    printf(
        'Value: %d-%d Count: %d, CountTo: %d',
        $data['value'],
        $data['highest_equivalent_value'],
        $data['count_at_index'],
        $data['count_to_index']
    );
}
```

**Comment by beberlei** [comment]
@stof  I know an OOP API is better, but its a pain to create in C / PHP Extension code. I tried but failed, so i went back to using the PHP4ish approach with resources.

**Comment by stof** [comment]
Then maybe provide it as an HTTP library on top of your low level PHP4ish API for now (and then, this OOP API could be moved to the C extension itself if someone with better extension development skills contributes to improve performances)

**Comment by beberlei** [comment]
@stof You mean HTTP => PHP-OOP or?

Yes that would make sense.

**Comment by stof** [comment]
yeah indeed. That's a weird typo :smile:
